# Generated by Django 4.0.4 on 2022-04-19 10:49

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_customuser_city_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('availability_status', models.CharField(choices=[('U', 'Unavailable'), ('A', 'Available')], default='U', max_length=20)),
            ],
            options={
                'db_table': 'team_members',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('team_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.teammembers')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=40, unique=True)),
                ('task_name', models.CharField(blank=True, max_length=40, null=True)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', max_length=40)),
                ('team_lead', models.CharField(max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('A', 'Assigned'), ('P', 'InProgress'), ('UR', 'UnderReview'), ('D', 'Done')], default='A', max_length=20)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.teammembers')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
